import Recipe from "~/models/Recipe";

export const SampleRecipes: Recipe[] = [
  new Recipe(1, "Yolkie on Toppie", ["Eggs", "Butter"], "Breakfast", "Cook eggs on skillet", true),
  new Recipe(2, "Pancakes", ["Flour", "Milk", "Eggs", "Sugar"], "Breakfast", "Mix ingredients and cook on a griddle."),
  new Recipe(3, "French Toast", ["Bread", "Eggs", "Milk", "Cinnamon"], "Breakfast", "Dip bread in mixture and fry."),
  new Recipe(4, "Omelette", ["Eggs", "Cheese", "Ham"], "Breakfast", "Cook eggs and fold with fillings."),
  new Recipe(5, "Breakfast Burrito", ["Tortilla", "Eggs", "Sausage", "Cheese"], "Breakfast", "Fill tortilla and roll."),
  new Recipe(6, "Yogurt Parfait", ["Yogurt", "Granola", "Berries"], "Breakfast", "Layer ingredients in a glass."),
  new Recipe(7, "Avocado Toast", ["Bread", "Avocado", "Salt", "Pepper"], "Breakfast", "Toast bread and top with avocado."),
  new Recipe(8, "Bagel Sandwich", ["Bagel", "Cream Cheese", "Turkey"], "Breakfast", "Assemble ingredients."),
  new Recipe(9, "Smoothie Bowl", ["Banana", "Berries", "Yogurt"], "Breakfast", "Blend and top with fruit."),

  new Recipe(10, "Grilled Cheese", ["Bread", "Cheddar", "Butter"], "Lunch", "Grill until golden."),
  new Recipe(11, "BLT Sandwich", ["Bread", "Bacon", "Lettuce", "Tomato"], "Lunch", "Layer ingredients."),
  new Recipe(12, "Chicken Caesar Salad", ["Chicken", "Lettuce", "Croutons", "Caesar Dressing"], "Lunch", "Mix together."),
  new Recipe(13, "Turkey Wrap", ["Tortilla", "Turkey", "Lettuce", "Tomato"], "Lunch", "Wrap ingredients."),
  new Recipe(14, "Tomato Soup", ["Tomatoes", "Cream", "Onion"], "Lunch", "Simmer and blend."),
  new Recipe(15, "Tuna Melt", ["Bread", "Tuna", "Cheese"], "Lunch", "Bake until cheese melts."),
  new Recipe(16, "Chicken Quesadilla", ["Tortilla", "Chicken", "Cheese"], "Lunch", "Cook until crispy."),
  new Recipe(17, "Greek Salad", ["Cucumber", "Tomato", "Feta", "Olives"], "Lunch", "Toss ingredients."),

  new Recipe(18, "Spaghetti Bolognese", ["Pasta", "Ground Beef", "Tomato Sauce"], "Dinner", "Cook pasta and combine with sauce."),
  new Recipe(19, "Chicken Alfredo", ["Chicken", "Pasta", "Cream"], "Dinner", "Cook pasta and mix with sauce."),
  new Recipe(20, "Beef Tacos", ["Ground Beef", "Tortillas", "Cheese"], "Dinner", "Cook beef and assemble tacos."),
  new Recipe(21, "Lasagna", ["Pasta", "Ricotta", "Mozzarella", "Tomato Sauce"], "Dinner", "Layer and bake."),
  new Recipe(22, "Chicken Stir Fry", ["Chicken", "Broccoli", "Soy Sauce"], "Dinner", "Stir fry ingredients."),
  new Recipe(23, "Grilled Salmon", ["Salmon", "Lemon", "Garlic"], "Dinner", "Season and grill."),
  new Recipe(24, "Beef Stew", ["Beef", "Potatoes", "Carrots"], "Dinner", "Slow cook until tender."),
  new Recipe(25, "BBQ Chicken", ["Chicken", "BBQ Sauce"], "Dinner", "Bake with sauce."),
  new Recipe(26, "Shrimp Fried Rice", ["Rice", "Shrimp", "Eggs", "Peas"], "Dinner", "Stir fry together."),
  new Recipe(27, "Chicken Parmesan", ["Chicken", "Parmesan", "Marinara"], "Dinner", "Bread, fry and bake."),
  new Recipe(28, "Stuffed Peppers", ["Bell Peppers", "Rice", "Ground Beef"], "Dinner", "Stuff peppers and bake."),
  new Recipe(29, "Shepherd's Pie", ["Ground Beef", "Mashed Potatoes"], "Dinner", "Bake until browned."),
  new Recipe(30, "Teriyaki Chicken", ["Chicken", "Teriyaki Sauce", "Rice"], "Dinner", "Cook chicken and glaze."),
  new Recipe(31, "Meatloaf", ["Ground Beef", "Breadcrumbs", "Egg"], "Dinner", "Bake until done."),
  new Recipe(32, "Baked Ziti", ["Pasta", "Marinara", "Mozzarella"], "Dinner", "Bake with cheese."),
  new Recipe(33, "Fish and Chips", ["Cod", "Potatoes"], "Dinner", "Fry fish and potatoes."),

  new Recipe(34, "Chocolate Cake", ["Flour", "Cocoa", "Eggs"], "Dessert", "Bake cake."),
  new Recipe(35, "Brownies", ["Chocolate", "Butter", "Flour"], "Dessert", "Bake until fudgy."),
  new Recipe(36, "Apple Pie", ["Apples", "Pie Crust", "Cinnamon"], "Dessert", "Bake until golden."),
  new Recipe(37, "Cheesecake", ["Cream Cheese", "Sugar", "Eggs"], "Dessert", "Bake then chill."),
  new Recipe(38, "Chocolate Chip Cookies", ["Flour", "Chocolate Chips", "Butter"], "Dessert", "Bake cookies."),
  new Recipe(39, "Ice Cream Sundae", ["Ice Cream", "Chocolate Syrup"], "Dessert", "Top with syrup."),
  new Recipe(40, "Banana Bread", ["Bananas", "Flour", "Sugar"], "Dessert", "Bake loaf."),
  new Recipe(41, "Lemon Bars", ["Lemon", "Sugar", "Flour"], "Dessert", "Bake and cool."),

  new Recipe(42, "Trail Mix", ["Nuts", "Raisins", "Chocolate Chips"], "Snack", "Mix ingredients."),
  new Recipe(43, "Popcorn", ["Popcorn Kernels", "Butter"], "Snack", "Pop and season."),
  new Recipe(44, "Fruit Salad", ["Apple", "Banana", "Grapes"], "Snack", "Chop and mix."),
  new Recipe(45, "Hummus and Veggies", ["Hummus", "Carrots", "Celery"], "Snack", "Serve together."),
  new Recipe(46, "Cheese and Crackers", ["Cheddar", "Crackers"], "Snack", "Arrange on a plate."),
  new Recipe(47, "Peanut Butter Toast", ["Bread", "Peanut Butter"], "Snack", "Toast and spread."),
  new Recipe(48, "Guacamole", ["Avocado", "Lime", "Onion"], "Snack", "Mash ingredients."),
  new Recipe(49, "Nachos", ["Tortilla Chips", "Cheese", "Jalapeños"], "Snack", "Bake until cheese melts."),
  new Recipe(50, "Deviled Eggs", ["Eggs", "Mayonnaise", "Mustard"], "Snack", "Fill egg halves."),
  new Recipe(51, "Energy Bites", ["Oats", "Peanut Butter", "Honey"], "Snack", "Mix and chill."),
];